sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/

# To disable posts (e.g., if you aren't planning on having any posts and Sculpin's watch mode complains):
#sculpin_content_types:
#    posts:
#        enabled: false